export const colors = {
  navy:     '#0f2354',
  navyDark: '#0a1a3a',
  red:      '#e8380a',
  redLt:    '#fce4dc',
  amber:    '#f5a623',
  blue:     '#185FA5',
  blueLt:   '#dce9f7',
  bgLight:  '#f0f4ff',
  bg:       '#f5f7fc',
  white:    '#ffffff',
  border:   '#e2eaf8',
  muted:    '#9aaccb',
  success:  '#2bcc6e',
  green:    '#2bcc6e',
  greenLt:  '#dff5e8',
};